[versions]

# plugins
shadow = "9.2.2"
buildconfig = "5.7.1"

# compile time processing
lombok = "1.18.42"

# general
guice = "7.0.0"
configura = "dev-a76adc6"
attache = "dev-5fad19f"
keystone = "dev-697f401"
commandant = "dev-0157bcc"
junit = "6.0.0"
mockito = "5.20.0"

# cloud
cloud-core = "2.0.0"
cloud-paper = "2.0.0-beta.13"
cloud-cooldown = "1.0.0-rc.1"
cloud-minecraft-extras = "2.0.0-beta.13"

# platform api versions
velocity = "3.4.0-SNAPSHOT"
spigot = "1.21.8-R0.1-SNAPSHOT"
paper = "1.21.8-R0.1-SNAPSHOT"

# platform hooks
packetevents = "2.10.1"

# adventure
adventure = "4.25.0"
adventure-platform-bukkit = "4.4.1"

# database
ebean = "17.1.1"
hikaricp = "7.0.2"
postgresql = "42.7.8"
mariadb = "3.5.6"

[libraries]

# compile time processing
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

# general
guice = { group = "com.google.inject", name = "guice", version.ref = "guice" }
configura = { group = "me.whereareiam", name = "configura", version.ref = "configura" }
keystone = { group = "me.whereareiam", name = "keystone", version.ref = "keystone" }
commandant = { group = "me.whereareiam", name = "commandant", version.ref = "commandant" }

# attache
attache-paper = { group = "me.whereareiam", name = "attache-paper", version.ref = "attache" }
attache-common = { group = "me.whereareiam", name = "attache-common", version.ref = "attache" }

# testing
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-platform = { group = "org.junit.platform", name = "junit-platform-launcher" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockito-junit = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockito" }

# cloud
cloud-core = { group = "org.incendo", name = "cloud-core", version.ref = "cloud-core" }
cloud-cooldowns = { group = "org.incendo", name = "cloud-processors-cooldown", version.ref = "cloud-cooldown" }
cloud-paper = { group = "org.incendo", name = "cloud-paper", version.ref = "cloud-paper" }
cloud-minecraft-extras = { group = "org.incendo", name = "cloud-minecraft-extras", version.ref = "cloud-minecraft-extras" }

# platform api
velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
spigot = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot" }
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }

# platform hooks
packetevents-spigot = { group = "com.github.retrooper", name = "packetevents-spigot", version.ref = "packetevents" }
packetevents-velocity = { group = "com.github.retrooper", name = "packetevents-spigot", version.ref = "packetevents" }

# adventure
adventure = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }
adventure-legacy = { group = "net.kyori", name = "adventure-text-serializer-legacy", version.ref = "adventure" }
adventure-plain = { group = "net.kyori", name = "adventure-text-serializer-plain", version.ref = "adventure" }
adventure-gson = { group = "net.kyori", name = "adventure-text-serializer-gson", version.ref = "adventure" }
adventure-platform-bukkit = { group = "net.kyori", name = "adventure-platform-bukkit", version.ref = "adventure-platform-bukkit" }

# database
ebean-core = { group = "io.ebean", name = "ebean-core", version.ref = "ebean" }
ebean-api = { group = "io.ebean", name = "ebean-api", version.ref = "ebean" }
hikaricp = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikaricp" }
postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }
mariadb = { group = "org.mariadb.jdbc", name = "mariadb-java-client", version.ref = "mariadb" }

[bundles]

adventure = ["adventure", "adventure-minimessage", "adventure-legacy", "adventure-plain", "adventure-gson"]
bukkit = ["spigot", "adventure-platform-bukkit"]
paper = ["paper", "cloud-core", "cloud-paper"]
velocity = ["velocity", "packetevents-velocity"]

[plugins]

shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }